// Mapeamento de cores por relevância dos temas médicos
// Total: 653 temas
// Cores: VERDE (alta), AMARELO (média), VERMELHO (baixa), ROXO (mínima)

type CorRelevancia = 'VERDE' | 'AMARELO' | 'VERMELHO' | 'ROXO';

export const TEMAS_CORES: { [tema: string]: CorRelevancia } = {
  "AVC Isquêmico 1": "VERDE",
  "AVC Isquêmico 2": "VERDE",
  "AVC Hemorrágico Intraparenquimatoso": "VERMELHO",
  "Hemorragia subaracnóide (HSA)": "AMARELO",
  "HIV": "VERDE",
  "Doenças oportunistas HIV": "VERDE",
  "Antibióticos I": "VERDE",
  "Antibióticos II": "VERDE",
  "Gasometria arterial I": "VERDE",
  "Introdução ao Extensivo": "VERDE",
  "Trauma: Introdução ao trauma": "VERDE",
  "Trauma: Vias Aéreas": "VERDE",
  "Trauma: Choque": "VERDE",
  "Trauma: Ressuscitação hemostática": "VERDE",
  "Trauma: Medidas Auxiliares e FAST": "AMARELO",
  "Trauma: Populações especiais": "VERMELHO",
  "Trauma: Revisão ABCDE": "VERDE",
  "Aleitamento materno": "VERDE",
  "Alimentação Infantil": "VERDE",
  "Desenvolvimento Infantil": "VERDE",
  "Transtornos do Desenvolvimento": "VERDE",
  "Concepção sobre saúde doença": "VERDE",
  "Níveis de Prevenção": "VERDE",
  "Modificações do Organismo Materno": "VERDE",
  "Assistência ao Pré-natal": "VERDE",
  "Ultrassonografia em Obstetricia": "VERDE",
  "Diabetes: Classificação, Fisiopatologia e Diagnostico do DM": "VERDE",
  "Meta terapêutica e tratamento não farmacológico do DM": "VERDE",
  "Antidiabeticos Orais e Subcutaneos 1": "VERDE",
  "Antidiabeticos Orais e Subcutaneos 2": "VERDE",
  "Insulinoterapia": "VERDE",
  "Complicações Crônicas do DM": "AMARELO",
  "Diabetes: emergências hiperglicêmicas (CAD e EHH)": "VERDE",
  "hiperglicemia hospitalar": "VERMELHO",
  "Dispepsia e antiácidos": "VERDE",
  "Estômago 2 Úlcera, H. pylori, Gastrite atrófica e dispepsia funcional": "VERDE",
  "disfagia, esofafite eosinofilica e acalasia": "VERMELHO",
  "DRGE": "VERDE",
  "Trauma: Trauma de Tórax I": "VERDE",
  "Trauma: Trauma de Tórax II": "AMARELO",
  "Trauma: Trauma Abdominal penetrante": "VERDE",
  "Trauma: Trauma Abdominal contuso": "VERDE",
  "Trauma: Trauma Abdominal específico - PARTE 1": "AMARELO",
  "Trauma: Trauma Abdominal específico - PARTE 2": "VERMELHO",
  "Nefro 1: Sindrome Nefritica, Nefrotica, SHU": "VERDE",
  "Nefro 2: DRC, LRA": "AMARELO",
  "Nefro 3: Miscelânea": "AMARELO",
  "Febre sem sinais localizatórios": "VERDE",
  "convulsões na emergência e traumatismo cranioencefalico leve": "VERDE",
  "maus tratos": "VERDE",
  "Indicadores de saúde": "VERDE",
  "Rastreamentos": "VERDE",
  "Prevenção 4 e 5": "VERDE",
  "Anatomia Pélvica Feminina": "VERDE",
  "Infecções e Gravidez": "VERDE",
  "Pneumonia Associada a Ventlção mecanica": "VERMELHO",
  "Princípios de ventilação mecânica": "VERDE",
  "Ventilação mecânica exercícios": "AMARELO",
  "Via aérea intubação e ventilação não invasiiva": "VERDE",
  "síndrome coronariana aguda com supra de ST (SCACSST)": "VERDE",
  "síndrome coronariana aguda sem supra de ST (SCASSST)": "VERDE",
  "Síndromes aórticas agudas": "AMARELO",
  "pericardite e miocardite": "VERMELHO",
  "Trauma: Trauma Cervical": "VERDE",
  "Trauma: Trauma Cervical especifico": "VERMELHO",
  "Trauma: Trauma musculoesquelético": "AMARELO",
  "Trauma: Trauma Cranioencefálico": "VERDE",
  "Trauma: Trauma Raquimedular": "VERDE",
  "Trauma: Encerramento": "VERDE",
  "Trauma: Trauma de pelve": "VERDE",
  "Abdome Agudo: Introdução": "VERDE",
  "Abdome Agudo Inflamatorio - Apendicite Aguda": "VERDE",
  "Abdome Agudo Inflamatorio - Colelitiase": "VERDE",
  "Abdome Agudo Inflamatorio - Colecistite": "VERDE",
  "Abdome Agudo Inflamatório - Colecistite - Visão crítica de Segurança": "AMARELO",
  "Alergia alimentar, refluxo e constipação": "VERDE",
  "diarreia crônica e doenças funcionais": "VERDE",
  "hepato na emergência": "VERMELHO",
  "crescimento e baixa estatura": "VERDE",
  "obesidade e síndrome metabólica": "VERDE",
  "puberdade": "VERDE",
  "Testes Diagnosticos: caracteristicas básicas": "VERDE",
  "Estática feral": "VERDE",
  "Mecanismos de Parto": "AMARELO",
  "Embriologia do Sistema Genital Femino": "AMARELO",
  "Malformações Mullerianas": "AMARELO",
  "Insuficiencia cardiaca - manejo ambulatorial": "VERDE",
  "Insuficiencia cardiaca - descompensações agudas": "AMARELO",
  "hipertensão (HAS)": "VERDE",
  "emergências hipertensivas": "VERDE",
  "oestoartrite": "AMARELO",
  "fibromialgia": "AMARELO",
  "espondiloartrites": "VERDE",
  "introdução as artrites e artrite reumatoide": "VERDE",
  "artrites microcristalinas (gota e CPPD)": "VERDE",
  "Abdome Agudo Inflamatório - Complicações": "AMARELO",
  "Abdome Agudo Inflamatório - Coledocolitíase": "AMARELO",
  "Abdome Agudo Inflamatório - Colangite": "VERDE",
  "Abdome Agudo Inflamatório - Pancreatite Aguda": "VERDE",
  "Abdome Agudo Inflamatório - Diverticulite Aguda": "VERDE",
  "Abdome Agudo Inflamatório - Abscesso Hepático": "AMARELO",
  "Abdome Agudo Obstrutivo": "VERDE",
  "Lítíase introdução": "VERDE",
  "lítíase - avaliação metabólica": "VERDE",
  "litíoase no PS": "VERDE",
  "Tratamento endoscópico de cálculo": "ROXO",
  "Litrotripisia extracutaneo (LECO)": "ROXO",
  "Pneumonias": "VERDE",
  "Bronquiloite e Coqueluche": "VERDE",
  "COVID": "VERMELHO",
  "desnutrição e vitaminas": "VERDE",
  "pediatria geral": "AMARELO",
  "Teste diagnóstico exercícios": "AMARELO",
  "testes diagnósticos": "VERDE",
  "Esteroidogênese": "AMARELO",
  "Assistência ao Parto": "VERDE",
  "PAC e hospitalar": "VERDE",
  "ASMA": "VERDE",
  "Derrame pleural": "VERDE",
  "Espirometria": "AMARELO",
  "Doença Pulmonar Obstrutiva Cronica (DPOC)": "VERDE",
  "Tabagismo": "VERDE",
  "avaliação global do hemograma": "VERDE",
  "anemias hipoproliferativas I": "VERDE",
  "Anemias hemolíticas adquiridas": "VERDE",
  "Anemias hipoproliferativas II": "AMARELO",
  "Anemias hemolíticas: Hereditárias": "AMARELO",
  "Abdome Agudo Perfurativo": "VERDE",
  "Abdome Agudo Vascular": "AMARELO",
  "Abdome Agudo Hemorrágico": "VERMELHO",
  "Abdome Agudo: Take-Home Message": "VERDE",
  "Hérnias: Anatomia da parede abdominal": "VERDE",
  "Hérnias: Hérnia Inguinal": "VERDE",
  "Hérnias: Hernioplastia inguinal": "AMARELO",
  "Escroto agudo": "VERDE",
  "Priapismo": "VERMELHO",
  "Fratura peniana": "ROXO",
  "PS - Trauma de Rim e de Ureter": "VERDE",
  "PS - Trauma de bexiga": "AMARELO",
  "PS - Trauma Genital": "ROXO",
  "PS - Trauma de uretra e estenose de uretra": "VERMELHO",
  "Infecções de vias aéreas superiores (IVAS)": "VERDE",
  "Suporte Avançado de vida e pediatria": "VERDE",
  "Dermatite atópica e lesões benigas do recém-nascido": "VERDE",
  "Dermatoses e Infecções de Partes Moles": "VERDE",
  "Farmadodermias": "VERMELHO",
  "Estudos longitudinais: coorte e caso controle": "VERDE",
  "Estudos transversais": "AMARELO",
  "Classificação dos estudos epidemiológicos": "VERDE",
  "Associação x causalidade": "VERDE",
  "Fisiologia menstrual": "VERDE",
  "Amenorreia Primária": "VERDE",
  "sífilis e uretrites infecciosas": "VERDE",
  "neurossifilis": "AMARELO",
  "Tuberculose pulmonar": "VERDE",
  "tuberculose extra pulmonar": "AMARELO",
  "tratamento de tuberculose e efeitos colaterais do RIPE": "VERDE",
  "Taquiarritmia": "VERDE",
  "Bradiarritimias": "VERDE",
  "Síncope": "VERDE",
  "Febre Reumática e Endocardite": "AMARELO",
  "Valvopatias": "VERMELHO",
  "BLS e ACLS": "VERDE",
  "Queimados - atendimento inicial": "VERDE",
  "Queimados - tratamento especifico": "VERMELHO",
  "Queimados - sequelas de queimadura": "VERMELHO",
  "Cirugia plastica: Cicatrização fisiologica": "AMARELO",
  "Cirugia plastica: Cicatrização patologica": "AMARELO",
  "Hérnias: Hernia Femoral": "AMARELO",
  "Hérnias: Hérnia Umbilical": "AMARELO",
  "Hérnias: Hérnias Incisionais": "VERMELHO",
  "Esofago: Introdução": "VERDE",
  "Esofago: Diagnosticos e diferenciais de disfagia": "AMARELO",
  "Acalasia": "AMARELO",
  "Barret": "VERMELHO",
  "Estômago: Anatomia": "VERDE",
  "Estômago - Adenocarcinoma Gástrico": "VERDE",
  "Estômago: CÃNCER, introdução e linfomas": "VERDE",
  "Estômago - complicações agudas pós gastrectomias": "AMARELO",
  "Reanimação neonatal": "VERDE",
  "infecções congênitas": "VERDE",
  "icterícia e colestase neonatal": "VERDE",
  "Cardiopatias congênitas": "VERDE",
  "hipertensão arterial sistêmicas (HAS)": "VERDE",
  "miocardite, spincope, insuficiência cardíaca": "AMARELO",
  "Revisando medidas de associação": "VERDE",
  "Ensaio clinico 1": "VERDE",
  "Ensaio clinico 2": "AMARELO",
  "Amenorreia Secundária": "VERDE",
  "Síndrome dos Ovários Policisticos": "VERDE",
  "Hiperprolactinemia": "AMARELO",
  "Glomerulopatias parte I": "VERDE",
  "Glomerulopatias parte II": "VERDE",
  "Disturbios Hidroeletrolíticos - outros (magnésio e fósforo)": "VERMELHO",
  "Disturbios do Sódio": "VERDE",
  "Distúrbios do Potássio": "VERDE",
  "Tireoidites & Síndrome do Eutireoidiano Doente": "AMARELO",
  "Nódulos e Câncer de Tireoide": "AMARELO",
  "Hipotireoidismo": "VERDE",
  "Fisiologia da Tireoide": "VERMELHO",
  "Hipertireoidismo": "VERDE",
  "Hérnias: Outras hérnias": "VERMELHO",
  "Hérnias: Síndrome compartimental intra-abdominal": "AMARELO",
  "Hérnias: Fechamento de parede abdominal": "ROXO",
  "Hérnias: Take-Home Message": "VERDE",
  "Estômago: GIST": "VERMELHO",
  "Estômago: Tumores neuroendócrinos": "VERMELHO",
  "Hernias de Hiato": "VERMELHO",
  "Obesidade: Princípios Gerais e Cirurgia Bariátrica": "VERDE",
  "Obesidade: Procedimentos Cirúrgicos": "VERMELHO",
  "Obesidade: Reganho de peso": "VERMELHO",
  "Obesidade: Complicações pós bariátrica": "AMARELO",
  "Uro-oncologia: próstata": "AMARELO",
  "Uro-oncologia: bexiga": "AMARELO",
  "Uro-oncologia: rim": "AMARELO",
  "Arboviroes": "VERDE",
  "Doenças Exantemáticas": "VERDE",
  "Distúrbios Metabólicos": "VERDE",
  "Triagens": "VERDE",
  "problemas, políticas e sistemas de saúde": "AMARELO",
  "Redes de atenção a saude e niveis de atenção": "VERDE",
  "Atenção Primária à Saúde - Parte 1": "VERDE",
  "Atenção Primária à Saúde - Parte 2": "VERDE",
  "Abortamento": "VERDE",
  "Gestação Ectópica": "VERDE",
  "Aborto Legal": "AMARELO",
  "Arboviroses": "VERDE",
  "Icterícias febris e febre maculosa": "VERDE",
  "Hepatites Virais": "VERDE",
  "Choque: abordagem inicial": "VERDE",
  "Choque: tipos de choque": "VERDE",
  "TEP": "VERDE",
  "HipertesÃ£o pulmonar": "VERMELHO",
  "Distúrbios do Sono": "VERMELHO",
  "Doença Pulmonar Intesticial (DPI)": "VERMELHO",
  "Nódulo Pulmonar": "VERMELHO",
  "PerioperatÃ³rio: Pré-operatório I": "VERDE",
  "PerioperatÃ³rio: Pré-operatório II": "VERDE",
  "Aneurisma de aorta I": "AMARELO",
  "Aneurisma de aorta II": "AMARELO",
  "TestÃ­culo": "VERMELHO",
  "Adrenal": "ROXO",
  "Pênis": "ROXO",
  "HPB": "VERDE",
  "Lesões por pressão": "AMARELO",
  "Cirurgia plástica: Anestésicos locais": "ROXO",
  "Cirurgia plástica: Fios de Sutura": "ROXO",
  "Coloproctologia: CA colorretal": "VERDE",
  "Coloproctologia: Síndromes Associadas ao CCR": "AMARELO",
  "Coloproctologia: Doenças Orificiais": "VERDE",
  "Coloproctologia: CEC Canal Anal": "ROXO",
  "Tuberculose": "VERDE",
  "Adenomegalias": "VERDE",
  "Infecções Fúngicas": "VERMELHO",
  "Kawasaki, vasculite por Iga e Febre Reumática": "VERDE",
  "Artrite Idiopática Juvenil": "VERDE",
  "Lei Orgânica de saúde: 8080/90": "VERDE",
  "Modelos de Proteção Social e história da saúde no brasil": "AMARELO",
  "princípios do SUS": "VERDE",
  "Placenta Prévia": "VERDE",
  "Descolamento Prematuro de Placenta": "VERDE",
  "Outros Sangramentos de Segunda Metade da Gestação": "AMARELO",
  "Doença Trofobástica Gestacional": "AMARELO",
  "Avaliação de enzimas hepáticas": "VERMELHO",
  "doenças hepáticas: CBP, CEP. HAI e doença de wilson": "ROXO",
  "cirrose conceitos gerais": "VERDE",
  "Gastro: Ascite + PBE": "VERDE",
  "Encefalopatia Hepática e Sìndrome Hepatorrenal": "VERDE",
  "Varizes esofágicas e síndrome hepatopulmonar": "VERDE",
  "Introdução a geriatria": "VERDE",
  "Avaliação geriátrica ampla": "VERDE",
  "Instabilidade Postural e quedas + Imobilidade": "AMARELO",
  "Vacinação do Idoso": "VERMELHO",
  "Iatrogenia no Idoso": "AMARELO",
  "PerioperatÃ³rio: REMIT e pós-operatório": "VERDE",
  "PerioperatÃ³rio: Complicações gerais": "VERDE",
  "Pâncreas e vias biliares: Cistos biliares": "ROXO",
  "Pâncreas e vias biliares: pólipo de vesícula biliar": "VERMELHO",
  "Pâncreas e vias biliares: câncer de vesícula": "ROXO",
  "Pâncreas e vias biliares: lesão iatrogênica da via biliar": "ROXO",
  "Trombose venosa profunda": "AMARELO",
  "Ferimento descolante": "VERMELHO",
  "Vacinação": "VERDE",
  "Meningite e Encefalite": "VERDE",
  "parasitoeses intestinais": "VERDE",
  "NOBs e NOAs": "VERDE",
  "Pacto pela saúde": "VERDE",
  "Lei Orgânica de Saúde: 8142/90": "VERDE",
  "propedeutica em uroginecologia": "VERDE",
  "cefaleias trigêmino-autonômicas": "AMARELO",
  "introdução às cefaleias primárias": "VERDE",
  "enxaqueca (migrânea)": "VERDE",
  "meningites e encefalites": "VERDE",
  "Acidentes com Animais Peçonhentos": "AMARELO",
  "Doenças Negligenciadas": "VERDE",
  "intoxicações exógenas": "VERDE",
  "Respiro e próximos passos": "VERDE",
  "HDA não varicosa": "VERDE",
  "HDA varicosa": "VERDE",
  "Corpo Estranho": "AMARELO",
  "HDB": "AMARELO",
  "Hemorragia digestiva média": "ROXO",
  "UND e disfunções miccionais": "ROXO",
  "Infertilidade": "ROXO",
  "Desafios finais": "ROXO",
  "Urologia: Síndrome da bexiga hiperativa e bexiga dolorosa": "ROXO",
  "Urologia: Bexiga neurogênica": "ROXO",
  "Incontinência urinária de esforço": "ROXO",
  "Medicina Sexual": "ROXO",
  "DSTs": "ROXO",
  "Cetoacidose Diabética (CAD)": "VERDE",
  "Hiperplasia Adrenal COngênita (HAC)": "VERDE",
  "Fibrose cística e diferenciais": "VERDE",
  "Decreto 7508/11": "VERDE",
  "Planejamento em Saúde": "VERDE",
  "Saúde Suplementar": "VERDE",
  "Financiamento do SUS": "VERDE",
  "Propedeutica Maária": "VERDE",
  "Principais SIntomas em Mastologia": "VERDE",
  "síndrome de guillain-barrÃ©": "AMARELO",
  "miastenia gravis": "VERMELHO",
  "Analgesia e Sedação": "VERMELHO",
  "Infecção de corrente sanguínea (ICS)": "AMARELO",
  "Drogas vasoativas (DVA)": "VERMELHO",
  "Cirurgia plástica: Enxertos": "VERMELHO",
  "Cirurgia plástica: Retalhos": "VERMELHO",
  "Principais retalhos": "ROXO",
  "contorno": "ROXO",
  "Fígado: Fígado para perdidos": "VERDE",
  "Fígado: Adenoma Hepático": "AMARELO",
  "Fígado: Hiperplasia Nodular Focal": "AMARELO",
  "Fígado: Hemangioma hepático": "AMARELO",
  "Fígado: Cisto Hepático": "VERMELHO",
  "Fígado: Metástases Hepáticas de CA colorretal - Parte 1": "ROXO",
  "Fígado: Metástases Hepáticas de CA colorretal - Parte 2": "ROXO",
  "Fígado: Carcinoma hepatocelular": "VERMELHO",
  "Fígado: Quiz": "AMARELO",
  "Introdução as anemias e hemocomponentes": "VERDE",
  "Anemia Falciforme": "VERDE",
  "Anemia Ferropriva e Talassemia": "VERDE",
  "Hemostasia e Distúrbios hemorragicos": "VERDE",
  "Ética em pesquisa clínica": "AMARELO",
  "Conceitos de MBE": "VERDE",
  "revisão sistemática": "AMARELO",
  "metanálise": "VERDE",
  "Classificação das Lesões Benignas": "AMARELO",
  "incontinência urinária de esforço": "VERDE",
  "incontinência urinária de urgência": "VERDE",
  "oncologia: cuidados paliativos": "VERMELHO",
  "Emergências oncológicas": "AMARELO",
  "Incidentaloma Adrenal": "AMARELO",
  "Síndrome de Cushing": "AMARELO",
  "Hiperaldosteronismo primário": "AMARELO",
  "Fisiologia e Anatomia da Adrenal": "VERMELHO",
  "Feocromocitoma": "VERMELHO",
  "fraturas de face": "VERMELHO",
  "paralisisa facial": "ROXO",
  "Trauma Vascular - miscelânea": "ROXO",
  "Trauma Vascular de Aorta": "ROXO",
  "Trauma Vascular de extremidades": "VERMELHO",
  "Isquemia de membros inferiores - OAA": "AMARELO",
  "Derrame Pleural": "AMARELO",
  "Exsudato Neutrofílico": "AMARELO",
  "Exsudato Linfocítico": "AMARELO",
  "Distúrbio de Diferenciação sexual": "VERMELHO",
  "Infecção de Trato Urinário (ITU)": "VERDE",
  "Diarreia Aguda": "VERDE",
  "Principios da Medicina de Familia e comunidade": "VERDE",
  "ESF: organização e funcionamento - parte 1": "VERDE",
  "prolapso genital": "VERDE",
  "estudo urodinâmico": "VERMELHO",
  "Síndromes hipertensivas na gestação - parte 1": "VERDE",
  "Síndromes hipertensivas na gestação - parte 2": "VERDE",
  "Vasculites de Grandes e médios vasos": "AMARELO",
  "vasculites de pequenos vasos": "AMARELO",
  "doença de behçet": "VERMELHO",
  "Miopatias Autoimunes Sistêmicas": "VERMELHO",
  "Osteoporose": "AMARELO",
  "Metabolismo do cálcio": "VERMELHO",
  "Hipercalcemias": "VERMELHO",
  "Hipocalcemias": "VERMELHO",
  "Distúrbios do Cálcio": "AMARELO",
  "Pâncreas e vias biliares: Adenocarcinoma de pâncreas O": "AMARELO",
  "Pâncreas e vias biliares: Pancreatite Crônica": "VERMELHO",
  "Isquemia de membros inferiores - OAC": "AMARELO",
  "Oncorirugia: Melanoma": "AMARELO",
  "Oncorirugia: Sarcoma": "VERMELHO",
  "Genética": "VERDE",
  "Sepse Neonatal": "VERDE",
  "Desconforto Respiratório Neonatal": "VERDE",
  "ESF - Financiamento e Programas Especiais": "VERDE",
  "ESF: organização e funcionamento - parte 2": "VERDE",
  "Corrimentos vaginais": "VERDE",
  "úlceras genitais": "VERDE",
  "Rotura Prematura de Membranas Ovulares": "VERDE",
  "Diabetes na Gestação": "VERDE",
  "Doença Inflamatoria intestinal": "AMARELO",
  "Diarreia crônica": "VERMELHO",
  "Diarreia aguda e colite pseudomembranosa": "VERDE",
  "Injúria Renal Aguda: Parte 1": "VERDE",
  "Injúria Renal Aguda: Parte 2": "AMARELO",
  "Prolactinomas": "VERMELHO",
  "Pâncreas e vias biliares: Neoplasias Císticas Pancreáticas": "ROXO",
  "Pâncreas e vias biliares: Outros tumores Periampulares": "VERMELHO",
  "Pâncreas e vias biliares: Tumores neuroendócrinos": "ROXO",
  "Estenose Carotídea Sintomática": "VERMELHO",
  "Estenose Carotídea Assintomática": "VERMELHO",
  "Pneumotórax": "ROXO",
  "Diagnósticos diferenciais das massas cervicais": "ROXO",
  "Esvaziamentos cervicais + anatomia": "VERMELHO",
  "Nutrição Neonatal": "ROXO",
  "Outras Doenças Neonatais": "VERMELHO",
  "medicina do adolescente": "AMARELO",
  "Ferramentas da APS/ESF": "VERDE",
  "Ferramentas da APS/ESF - parte 1": "VERDE",
  "Ferramentas da APS/ESF - parte 2: equipes e-MULTI": "AMARELO",
  "violência sexual": "VERDE",
  "doença inflamatória pélvica aguda": "VERDE",
  "Sofirmento Fetal agudo": "VERDE",
  "Doença renal crônica I: Avaliação de função renal, causas e estratificação": "AMARELO",
  "Doença Renal Crônica II: Tratamento": "VERMELHO",
  "Infecção urinária na prática clínica": "VERDE",
  "Epilepsia": "AMARELO",
  "Esclerose Múltipla": "VERMELHO",
  "Neuromielite Ãpitica (NMO)": "VERMELHO",
  "Doença de Parkinson": "VERMELHO",
  "TireÃ³ide I - anatomia, fisiologia e tireoidites": "VERMELHO",
  "TireÃ³ide II - nódulo e bócio.": "VERMELHO",
  "TireÃ³ide III - carcinoma bem diferenciado": "VERMELHO",
  "TireÃ³ide IV - carcinoma medular e anaplásico": "ROXO",
  "Cirurgia Geral: Videolaparoscopia": "AMARELO",
  "Eletrocirurgia": "ROXO",
  "Síndrome de Fournier": "AMARELO",
  "QuilotÃ³rax": "ROXO",
  "Insuficiência crônica": "VERMELHO",
  "Síndromes compressivas": "ROXO",
  "Nutrologia em Pediatria": "VERMELHO",
  "cuidados paliativos em pediatria": "VERMELHO",
  "Intoxicações e Peçonhentos": "VERDE",
  "Vigilancia em Saúde": "VERDE",
  "MCCP": "VERDE",
  "Avaliação da Vitalidade Fetal": "VERDE",
  "Sofirmento Fetal Cronico": "AMARELO",
  "Anticoncepção em situações especiais": "AMARELO",
  "Anticoncepção - métodos disponíveis": "VERDE",
  "Fragilidade": "AMARELO",
  "Incontinência urinária no idoso": "VERMELHO",
  "Insuficiência cognitiva: Delirium no idoso": "AMARELO",
  "Insuficiência Cognitiva: Demência": "VERDE",
  "Depressão no idoso": "VERDE",
  "Transtorno de humor parte I": "AMARELO",
  "Transtorno de humor parte II : antidepresivos": "AMARELO",
  "Transtorno de humor parte III : síndrome maníaca e transtorno bipolar": "VERMELHO",
  "Transtorno de humor parte IV : fatores de risco para suicídio": "AMARELO",
  "Emergências psiquátricas": "VERDE",
  "Doença Inflamatória Intestinal - parte 1": "ROXO",
  "Doença Inflamatória Intestinal - parte 2": "ROXO",
  "Nutrição perioperatória": "ROXO",
  "Avaliação pré-anestésica": "ROXO",
  "Paratieoide I - conceitos iniciais": "ROXO",
  "Paratireoide II - Hiperparatireoidismo primario": "ROXO",
  "Paratireoide III - Hiperparatireoidismo secundario e terciario": "ROXO",
  "anomalias congenitas em cabeça e pescoço": "AMARELO",
  "câncer de pele não melanoma": "VERMELHO",
  "Mama - ginecomastia": "ROXO",
  "Mama - hipertrofia mamária": "ROXO",
  "Mama - BIA, ALCL e síndrome Asia": "ROXO",
  "Mama - Reconstrução de mama": "ROXO",
  "Tumores e Leucemias": "VERDE",
  "Ingestão e Aspiração de Corpo Estranho e BRUE": "VERDE",
  "ReSOAP": "AMARELO",
  "Processo epidêmico": "VERDE",
  "Anticoncepção - FUNDAMENTOS": "VERDE",
  "cuidados à saude LGBTQIAPN+": "AMARELO",
  "Trabalho de parto prematuro": "VERDE",
  "colo curto e incompetencia istmocervical": "VERDE",
  "Fisiologia da Coagulação": "AMARELO",
  "Hemato: Distúrbios da Hemostasia": "AMARELO",
  "Obesidade Conceitos Gerais + Tto Não Farmacológico": "AMARELO",
  "Obesidade Tto  Farmacológico e cirugico": "VERMELHO",
  "síndrome metabólica": "VERDE",
  "Doença hepática gordurosa associada a disfunção metabólica (MAFLD)": "VERMELHO",
  "Dislipidemia - classificação e diagnóstico": "AMARELO",
  "tratamento das dislipidemias": "AMARELO",
  "Sepse Pediátrica": "AMARELO",
  "Disturbios hidroeletrolitico": "AMARELO",
  "Disturbio ácido Básico": "AMARELO",
  "Choque e Drogas Vasoativas": "AMARELO",
  "Abordagem Familiar": "VERDE",
  "Abordagem comunitária": "VERDE",
  "gemelaridade": "AMARELO",
  "Restrição de Crescimento intrauterino": "VERDE",
  "Sangramento uterino anormal - Leiomioma": "VERDE",
  "Sangramento uterino anormal - fundamentos": "VERDE",
  "Púrpura Trombocitopênica Trombótica (PTT)": "VERMELHO",
  "hemoterapia": "VERMELHO",
  "Síndromes Medulares": "VERMELHO",
  "Discrasias Plasmocitárias": "AMARELO",
  "Alergia 1: Reações de hipersensibilidade: Parte 01 e 02": "AMARELO",
  "Alergia 2: Rinite Angioedema e DPV": "VERMELHO",
  "Lesões Elementares": "ROXO",
  "Hanseníase": "AMARELO",
  "Dermatoses Bolhosas": "ROXO",
  "Psoríase": "ROXO",
  "Preparo de Cólon": "VERMELHO",
  "Pólipos colorretais": "VERMELHO",
  "CA colorretal precoce": "VERMELHO",
  "Cirurgia Vascular: Pé diabético": "AMARELO",
  "Cirurgia Vascular: Vasculites": "ROXO",
  "Síndromes Febris": "VERMELHO",
  "Imunodeficiências para o Pediatra": "VERDE",
  "Políticas Públicas de Saúde I: Populações Especiais (saúde indígena, população negra e população LGBTQIA+)": "AMARELO",
  "Políticas Públicas de Saúde II: políticas setoriais": "AMARELO",
  "Puerpério Fisiológico": "AMARELO",
  "Puerpério Patológico": "AMARELO",
  "Sangramento uterino anormal - Adenomiose": "VERDE",
  "endometriose": "VERDE",
  "Esclerose Sistêmica": "AMARELO",
  "Síndrome de Sjogren": "VERMELHO",
  "Lúpus": "VERDE",
  "Parasitoses Intestinais": "AMARELO",
  "Doenças Virais e Pandêmicas": "VERDE",
  "Região inguinal e distopias testiculares": "VERMELHO",
  "Defeitos da parede adominal": "AMARELO",
  "Cirurgia Torácica: Câncer de Pulmão (parte 1)": "AMARELO",
  "Cirurgia Torácica: Câncer de Pulmão (parte 2)": "AMARELO",
  "Ortopedia: Geral": "AMARELO",
  "Cirurgia Vascular: Síndrome do desfiladeiro torácico": "ROXO",
  "Politrauma, Afogamento e Queimadura": "AMARELO",
  "TCE Grave e Morte encefálica": "VERMELHO",
  "ética em pediátria - 1": "AMARELO",
  "ética em pediátria - 2": "AMARELO",
  "Políticas Específicas: Reforma Psiquiátrica e RAPS - rede de atenção psicossocial": "VERDE",
  "Habilidades de Comunicação - Parte 1": "AMARELO",
  "Hemorragia pós parto": "VERDE",
  "Alterações Colpocitológicas e condutas": "VERDE",
  "câncer de colo de útero": "VERDE",
  "Doenças da vulva e da vagina": "VERMELHO",
  "Linfomas": "AMARELO",
  "Leucemias": "AMARELO",
  "Cirurgia Torácica: Câncer de Pulmão (parte 3)": "VERMELHO",
  "Cirurgia Torácica: Câncer de Pulmão (QUIZ)": "VERMELHO",
  "Mediastino": "ROXO",
  "Complicações Mediastinais": "ROXO",
  "Pós-Operatório": "VERMELHO",
  "Ortopedia: Traumatologia": "AMARELO",
  "Psiquiatria da Infância e Adolescência": "VERMELHO",
  "Sono e seus distúrbios": "VERMELHO",
  "malformações do sistenma nervoso": "ROXO",
  "Saúde Planetária": "AMARELO",
  "Habilidades de Comunicação - Parte 2": "AMARELO",
  "Câncer de Mama - rastreamento": "VERDE",
  "Câncer de Mama - fatres de risco e CDIS": "VERDE",
  "Câncer de Mama - doença invasiva": "AMARELO",
  "Tumores Anexiais": "AMARELO",
  "Câncer de Ovário": "AMARELO",
  "Transtorno de Ansiedade": "AMARELO",
  "Transtorno Psicótico": "VERMELHO",
  "Transtornos Relacionados a Substâncias - Álcool": "AMARELO",
  "Transtorno alimentares e somatoformes": "VERMELHO",
  "Transtorno de personalidade": "VERMELHO",
  "rastreamentos": "VERMELHO",
  "Doenças Traqueais": "ROXO",
  "Bronquiectasias e hemoptise": "ROXO",
  "Bônus - Doenças da Parede Torácica": "ROXO",
  "Quiz Doenças Traqueais": "ROXO",
  "Quiz Doenças de Parede Torácica": "ROXO",
  "Quiz Bronquiectasia e hemoptise": "ROXO",
  "Doenças congênitas": "VERMELHO",
  "Transplante Cardíaco": "VERMELHO",
  "Cefaleias na infância": "AMARELO",
  "Hipertensão Intracraniana e Hidrocefalia": "ROXO",
  "Epilepsias na Infância - Parte 1": "ROXO",
  "Epilepsias na Infância - Parte 2": "ROXO",
  "Epilepsias na Infância - Parte 3": "ROXO",
  "Saúde do trabalhador: Pneumoconicoses": "VERDE",
  "Medicina do trabalho: acidente de trabalho": "VERDE",
  "Síndrome climatéria": "VERDE",
  "terapia de reposição hormonal": "AMARELO",
  "hiperplasia endometrial": "VERDE",
  "câncer de endomÃ©trio": "AMARELO",
  "Otologia I": "ROXO",
  "Oftalmologia para o generalista - parte I": "ROXO",
  "Rinologia": "ROXO",
  "Cirurgia Infantil: Atresia de esôfago e doença da via biliar": "ROXO",
  "Cirurgia Infantil: Torax pediátrico": "ROXO",
  "CIPE no PS": "AMARELO",
  "Vômitos no RN / lactente": "VERDE",
  "Ortopedia: Pediátrica": "VERMELHO",
  "Doença da Aorta": "ROXO",
  "Doença coronariana": "ROXO",
  "Sedoanalgesia e SequÃªncia Rápida de Intubação": "AMARELO",
  "Insuficiência Respiratória e Síndrome do Desconforto Respiratório Agudo Pediátrico (PARDS)": "VERMELHO",
  "Ventilação Mecânica": "VERMELHO",
  "Ortopedia Pediátrica": "AMARELO",
  "Medicina legal: declaração de óbito, atestado e laudos": "AMARELO",
  "ética médica": "VERDE",
  "Técnicas de Reprodução Assistida": "AMARELO",
  "Diferença no desenvolvimento Secual": "VERMELHO",
  "Puberdade Precoce e Tardia": "AMARELO",
  "Bucofaringolaringologia I": "ROXO",
  "Cirurgia Infantil: Doenças cervicais na infância": "ROXO",
  "Cirurgia infantil: Tumores da infância": "ROXO",
  "Tumores do Intestino Delgado": "ROXO",
  "SII": "ROXO",
  "Endometriose": "ROXO",
  "Distúrbios do assoalho pélvico": "ROXO",
  "Cisto pilonidal": "ROXO",
  "Monitorização em anestesia (Profundidade anestésica, Junção neuromuscular, Capnografia e Oximetria)": "ROXO",
  "Técnicas anestésicas 1: Anestesia geral (agentes opióides, indutores e BNM)": "ROXO",
  "Doenças Valvares": "ROXO",
  "Cirurgia PED no PS": "ROXO",
  "Uropediatria e Hérnias": "ROXO",
  "Malformações congênitas": "ROXO",
  "Saúde do trabalhador: lesões musculoesqueléticas": "VERMELHO",
  "Saúde do trabalhador: intoxicações, pairo e bournour": "AMARELO",
  "Trombofilias na Gestação e Puerpério": "AMARELO",
  "Distúrbios Psiquiátricos na Gestação e Pós parto": "VERMELHO",
  "outras urgências ginecológicas": "VERMELHO",
  "cirurgia ginecológica": "AMARELO",
  "Bucofaringolaringologia II": "ROXO",
  "Resumão/encerramento": "VERDE",
  "Doenças cirúrgicas do Baço": "ROXO",
  "Técnicas anestésicas 2: Anestésicos locais e anestesia regional (bloqueios de nervo periférico)": "ROXO",
  "Técnicas anestésicas 3: Bloqueio de neuroeixo (Raquianestesia e Peridural)": "ROXO",
  "Neurocirurgia: Emergências neurocirúrgicas": "ROXO",
  "Neurocirurgia: demais assuntos": "ROXO",
  "Oftalmo Pediatria 1": "ROXO",
  "Oftalmo Pediatria 2: doenças pediátricas": "ROXO",
  "Otorrino Pediatria 1": "ROXO",
  "Otorrino Pediatria 2": "ROXO",
  "Doenças sistêmicas com acometimento do Sistema nervoso central": "ROXO",
  "Outros tópicos de Saúde Coletiva: Avaliação em Saúde, tecnolgoia em Saúde e Segurança do Paciente": "VERMELHO",
  "Saúde do trabalhador: dermatoses": "VERMELHO",
  "Malformações Congênitas": "AMARELO",
  "Rastreamento de Aneuploidias": "AMARELO",
  "Procedimentos invasisvos em medicina fetal": "VERMELHO",
  "Doenças Hemolítica Perinatal": "AMARELO"
};

// Função auxiliar para obter a cor de um tema
export function getCorTema(tema: string): CorRelevancia {
  // Normalizar o tema removendo acentuações variadas para melhor match
  const temaNormalizado = tema.trim();

  // Busca direta
  if (TEMAS_CORES[temaNormalizado]) {
    return TEMAS_CORES[temaNormalizado];
  }

  // Se não encontrar, retorna cor padrão (AMARELO - média relevância)
  console.warn(`Tema não encontrado no mapeamento de cores: "${tema}"`);
  return 'AMARELO';
}

// Mapeamento de cores para estilos CSS
export const COLOR_STYLES: {
  [key in CorRelevancia]: {
    bg: string;
    border: string;
    text: string;
    dot: string;
    label: string;
  }
} = {
  'VERDE': {
    bg: 'bg-green-50',
    border: 'border-green-400',
    text: 'text-green-900',
    dot: 'bg-green-500',
    label: 'Alta'
  },
  'AMARELO': {
    bg: 'bg-yellow-50',
    border: 'border-yellow-400',
    text: 'text-yellow-900',
    dot: 'bg-yellow-500',
    label: 'Média'
  },
  'VERMELHO': {
    bg: 'bg-red-50',
    border: 'border-red-400',
    text: 'text-red-900',
    dot: 'bg-red-500',
    label: 'Baixa'
  },
  'ROXO': {
    bg: 'bg-purple-50',
    border: 'border-purple-400',
    text: 'text-purple-900',
    dot: 'bg-purple-500',
    label: 'Mínima'
  }
};
